In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.backends.backend_pdf
import matplotlib as mpl
import copy

In [2]:
cytoPath_read = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str_dr.txt"
cytoPath_write = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_ordered_str_dr.txt"

cytobands_df = pd.read_csv(cytoPath_read, sep="\t")#, header=None))

cytobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,DR_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.326
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084,0.282
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056,0.275
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049,0.405
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056,0.404
...,...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037,0.015
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062,0.013
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082,0.006
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026,0.002
862,chrY,26600000,57227414,q12,gvar,30627414,0.006,0.001

In [3]:
cytobands_df["Chromossome"].unique()

array(['chr1', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15',
       'chr16', 'chr17', 'chr18', 'chr19', 'chr2', 'chr20', 'chr21',
       'chr22', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9',
       'chrM', 'chrX', 'chrY'], dtype=object)

In [3]:
def reorder_cytobands_df(cdf):
    chr_numbers = []
    for chromosome in cdf["Chromossome"]:
        if chromosome == "chrM":
            chr_numbers.append(23)
        elif chromosome == "chrX":
            chr_numbers.append(24)
        elif chromosome == "chrY":
            chr_numbers.append(25)
        elif len(chromosome) == 4:
            chr_numbers.append(int(chromosome[-1]))
        elif len(chromosome) == 5:
            chr_numbers.append(int(chromosome[-2:]))
    cdf.insert(len(cdf.columns), "Chromosome_n", chr_numbers, True)
    return cdf.sort_values(['Chromosome_n', 'First_index'])

In [5]:
cytobands_df = reorder_cytobands_df(cytobands_df)

In [6]:
cytobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,DR_density,Chromosome_n
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.326,1
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084,0.282,1
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056,0.275,1
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049,0.405,1
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056,0.404,1
...,...,...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037,0.015,25
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062,0.013,25
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082,0.006,25
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026,0.002,25
862,chrY,26600000,57227414,q12,gvar,30627414,0.006,0.001,25

In [7]:
cytobands_df = cytobands_df.drop(columns=['Chromosome_n'])

In [4]:
def writeNewtxt(file_path, df):
    """Writes a pandas dataframe into txt, columns separated by tabs ("\t")
    """
    f = open(file_path, 'w')
    df_cols = ""
    for col in df.columns[:-1]:
        df_cols += col + "\t"
    df_cols += df.columns.values[-1]+ "\n"
    f.write(str(df_cols))
    for row in df.values:
        df_row = ""
        for col in row[:-1]:
            df_row += str(col) + "\t"
        df_row += str(row[-1])+ "\n"
        f.write(df_row)
    f.close

In [9]:
writeNewtxt(cytoPath_write, cytobands_df)

In [5]:
def execute(cytoband_read, cytoband_write):
    cytoband_df = pd.read_csv(cytoband_read, sep="\t")#, header=None))
    cytoband_df = reorder_cytobands_df(cytoband_df)
    cytoband_df = cytoband_df.drop(columns=['Chromosome_n'])
    writeNewtxt(cytoband_write, cytoband_df)

In [6]:
cytoband_read = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str_dr_dg.txt"
cytoband_write = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str_dr_dg_ordered.txt"
execute(cytoband_read, cytoband_write)