In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def add_headersToDf(dataframe):
    return dataframe.rename(columns={0: 'Chromossome', 1: 'First_index', 2: 'Last_index', 3: 'Citoband', 4: 'Unkown'})

In [3]:
def subtract_lastindex(dataframe):
    new_row = []
    for row in dataframe['Last_index']:
        new_row.append(row - 1)
    
    dataframe.drop('Last_index', axis = 1, inplace=True)

    dataframe.insert(2, "Last_index", new_row, True)

In [4]:
def add_sizeColumn(dataframe):
    sizes = []
    for row in range(len(dataframe.values)):
        size = dataframe["Last_index"][row] - dataframe["First_index"][row]
        sizes.append(size)
    dataframe.insert(len(dataframe.columns), "Size", sizes, True)

In [6]:
######################################## calc densities ############################################
def calc_STRDensity(cytobands_df, str_df, col_name = "STRs_density"):
    densities = []
    for chrom in cytobands_df["Chromossome"].unique():             
        print("searching cytobands in chromossome: ", chrom)
        chr_cytobands = cytobands_df.loc[cytobands_df['Chromossome'] == chrom]
        chr_size = chr_cytobands["Last_index"][chr_cytobands.index[-1]]+1
        cytobands_strs = np.zeros((chr_size), dtype=int)
        chr_strs = str_df.loc[str_df['FastaHeader'] == chrom]
        #percorrer o dataset pelas vulnerabilidades no cromossoma e anotar na lista np.zeroes
        for row in chr_strs.index:
            cytobands_strs[chr_strs["FirstIndex"][row]: chr_strs["LastIndex"][row]]+=1
        #Calculo da densidade para cada cytoband
        for cytoband in chr_cytobands.index:
            cytoband_array = cytobands_strs[int(chr_cytobands["First_index"][cytoband]):int(chr_cytobands["Last_index"][cytoband])+1]
            dr_length = np.count_nonzero(cytoband_array)
            cytoband_length = chr_cytobands["Size"][cytoband]
            density = dr_length/cytoband_length
            densities.append(round(density, 10))
        
    cytobands_df.insert(len(cytobands_df.columns), col_name, densities, True)

In [7]:
def writetxt(txt_path, df):
    with open(txt_path, 'w') as f:
        df_string = df.to_string(header=False, index=False)
        f.write(df_string)
        f.close

def writeNewtxt(file_path, df):
    """Writes a pandas dataframe into txt, columns separated by tabs ("\t")
    """
    f = open(file_path, 'w')
    str_cols = ""
    for col in df.columns[:-1]:
        str_cols += col + "\t"
    str_cols += df.columns.values[-1]+ "\n"
    f.write(str(str_cols))
    for row in df.values:
        str_row = ""
        for col in row[:-1]:
            str_row += str(col) + "\t"
        str_row += str(row[-1])+ "\n"
        f.write(str_row)
    f.close

In [8]:
citoPath_read = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_complete.txt"
citoPath_write = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str.txt"
#STRPath_read = "/home/androx/Documents/trabalho/datasets/STR/HomosapiensHG38_nov2014/HomosapiensHG38_FullGenome_processed.txt"
STRPath_read = "/home/androx/Documents/trabalho/datasets/STR/HomosapiensHG38_jan2016/HumanGenome_processed.txt"

citobands_df = add_headersToDf(pd.read_csv(citoPath_read, sep="\t"))#, header=None))
str_df = pd.read_csv(STRPath_read, sep="\t")
#print("columns: ", cito_dataframe.columns)

#subtract_lastindex(citobands_df)
#add_sizeColumn(citobands_df)
#print(citobands_df)

In [9]:
str_df

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
0,184820957,10001,10468,6,77.125000,468,chr1,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,TAACCC,cgcggtaccctcagccggcccgcccgcccgggtctgacctgaggag...,p36.33
1,184820958,10628,10800,29,5.965517,173,chr1,gcggtgctctccgggtctgtgctgaggagaacgcaactccgccgtt...,AGGCGCGCCGCGCCGGCGCAGGCGCAGAG,cacatgctagcgcgtcggggtggaggcgtggcgcaggcgcagagag...,p36.33
2,184820959,10823,10865,23,1.956522,43,chr1,aggcgcgccgcgccggcgcaggcgcagacacatgctagcgcgtcgg...,GAGGCGCGCCGCGCAGGCGCAGA,gcgcagagacacatgctaccgcgtccaggggtggaggcgtggcgca...,p36.33
3,184820960,10758,10997,76,3.210526,240,chr1,cgcagagaggcgcgccgcgccggcgcaggcgcagagaggcgcgccg...,GGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAC...,cgcaagcctacgggcgggggttgggggggcgtgtgttgcaggagca...,p36.33
4,184820961,11226,11447,124,1.854839,222,chr1,cttgcagccgggcactacaggacccgcttgctcacggtgctgtgcc...,CGCCCCCTGCTGGCAACTAGGGAAACTGCAGGGCCCTCTTGCTCAA...,CCAACAGTACTGGCGGATTATAGGGAAACACCCGGAGCATATGCTG...,p36.33
...,...,...,...,...,...,...,...,...,...,...,...
1199623,186020580,57216407,57217320,6,150.222229,914,chrY,cctaatgcacacatgatacccaaaatataacacccacattcctcat...,TTAGGG,gtggtgtgtgggtgtgtgtgggtgtggtgtgtgtgggtgtggtgtg...,q12
1199624,186020581,57217317,57217414,6,16.375000,98,chrY,gttaggggttaggggttaggggttaggggttagggttagggttagg...,GGGTGT,TNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12
1199625,186020582,57217317,57217415,13,7.714286,99,chrY,gttaggggttaggggttaggggttaggggttagggttagggttagg...,GGGTGTGGTGTGT,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12
1199626,186020583,57217319,57217413,2,49.500000,95,chrY,taggggttaggggttaggggttaggggttagggttagggttagggt...,GT,gTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12
1199627,186020584,57217317,57217415,53,1.924528,99,chrY,gttaggggttaggggttaggggttaggggttagggttagggttagg...,GGGTGTGGTGTGTGGGTGTGGGTGGGTGGGTGTGGTGTGTGGGTGT...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12

In [10]:
citobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density
0,chr1,0,2299999,p36.33,gneg,2299999,0.088
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056
...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026
862,chrY,26600000,57227414,q12,gvar,30627414,0.006

In [11]:
str_df["Citoband"].unique

<bound method Series.unique of 0          p36.33
1          p36.33
2          p36.33
3          p36.33
4          p36.33
            ...
1199623       q12
1199624       q12
1199625       q12
1199626       q12
1199627       q12
Name: Citoband, Length: 1199628, dtype: object>

In [12]:
calc_STRDensity(citobands_df, str_df)

searching cytobands in chromossome:  chr1
searching cytobands in chromossome:  chr10
searching cytobands in chromossome:  chr11
searching cytobands in chromossome:  chr12
searching cytobands in chromossome:  chr13
searching cytobands in chromossome:  chr14
searching cytobands in chromossome:  chr15
searching cytobands in chromossome:  chr16
searching cytobands in chromossome:  chr17
searching cytobands in chromossome:  chr18
searching cytobands in chromossome:  chr19
searching cytobands in chromossome:  chr2
searching cytobands in chromossome:  chr20
searching cytobands in chromossome:  chr21
searching cytobands in chromossome:  chr22
searching cytobands in chromossome:  chr3
searching cytobands in chromossome:  chr4
searching cytobands in chromossome:  chr5
searching cytobands in chromossome:  chr6
searching cytobands in chromossome:  chr7
searching cytobands in chromossome:  chr8
searching cytobands in chromossome:  chr9
searching cytobands in chromossome:  chrM
searching cytobands in chromossome:  chrX
searching cytobands in chromossome:  chrY

In [13]:
citobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,STRs_density
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.088
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084,0.084
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056,0.056
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049,0.049
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056,0.056
...,...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037,0.037
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062,0.062
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082,0.082
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026,0.026
862,chrY,26600000,57227414,q12,gvar,30627414,0.006,0.006

In [14]:
#print(str_df)

In [15]:
#writetxt(citoPath_write, citobands_df)
writeNewtxt(citoPath_write, citobands_df)

# Investigação das cytobandas com densidade de STR a 100% e das correspondentes instacias de STR

In [16]:
citobands_df_dens1 = citobands_df.loc[citobands_df['STR_Density'] == 1]
citobands_df_dens1

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,STRs_density
185,chr13,16500000,17699999,p11.1,acen,1199999,1.0,1.0
253,chr15,17500000,18999999,p11.1,acen,1499999,1.0,1.0
455,chr21,10900000,11999999,p11.1,acen,1099999,1.0,1.0
469,chr22,13700000,14999999,p11.1,acen,1299999,1.0,1.0

#### As cytobandas com densidade 1 são as cytobandas p11.1 dos cromossomas chr13, chr15, chr21 e chr22

In [17]:
chrom_aflicted = citobands_df_dens1["Chromossome"].unique()

## É visivel que as instancias de cytobanda não encontrada correspondem aos cromossomas e às cytobandas com densidade de STR de 1

In [18]:
str_df_investigate = str_df.loc[str_df['Citoband'] == "citoband not found"]
str_df_investigate

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
255771,185076728,16003398,18051248,171,12013.000000,2047851,chr13,gaatgggatatttctgagaagttggaggcctatatcgaaaaagaaa...,ATTCTCAGAAACTTCTTTGTGATGTGTGCATTCAACTCACAGAGTT...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,citoband not found
255772,185076729,16000001,18051248,1364,1504.000000,2051248,chr13,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,AGCATTCTCAGAAACTTCTTTGTGATGTGTGCACTCAACTAACAGA...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,citoband not found
328845,185149802,17083674,19725208,171,15472.700195,2641535,chr15,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,AGCATTCTGAGAAACTTCTTTGTGATGTGTGCATTCAACTCACAGA...,aaatttcgttggaagcgggaaaaccttcatataaaatctagacagC...,citoband not found
328846,185149803,17083685,19725208,513,5162.600098,2641524,chr15,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGcattc...,AAACTTCTTTGTGATGTGTGCATTCAACTCACAGAGTTGAACCTTT...,aaatttcgttggaagcgggaaaaccttcatataaaatctagacagC...,citoband not found
632619,185453576,10867958,12915808,171,12013.000000,2047851,chr21,gaatgggatatttctgagaagttggaggcctatatcgaaaaagaaa...,ATTCTCAGAAACTTCTTTGTGATGTGTGCATTCAACTCACAGAGTT...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,citoband not found
632620,185453577,10864561,12915808,1364,1504.000000,2051248,chr21,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,AGCATTCTCAGAAACTTCTTTGTGATGTGTGCACTCAACTAACAGA...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,citoband not found
649470,185470427,13021432,15054318,171,11924.900391,2032887,chr22,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAACAT...,AGAAACTTCTTTGTGATGTGTGCATTCAACTCACAGAGTTGAACAT...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,citoband not found
649472,185470429,13021432,15054318,1363,1490.400024,2032887,chr22,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAACAT...,AGAAACTTCTTTGTGATGTGTGCACTCAACTAACAGAGTTGAACCT...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,citoband not found

#### As colunas First e Last Index, assim como "ArrayLength" de facto revelam sequences de STR de muito grandes dimensões nos cromossomas e cytobandas em questão.

In [19]:
str_df_chr13Investigate = str_df.loc[(str_df['FastaHeader'] == "chr13") & (str_df['Citoband'] == "p11.1")]
str_df_chr13Investigate

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
255773,185076730,16755312,16755385,37,2.000000,74,chr13,atataaactagacagaagcattttcataaacttgtttgtgatgtgt...,TCAGCTAACAGACGTGGATCTCTCTTTTGATACAGCA,gttttgaaaaacactttttgttgaatctgcaagtggacatttggat...,p11.1
255774,185076731,16824956,16824987,14,2.357143,32,chr13,ctcataaacttgttttgatgtgtgaactcagctaacagaggtggat...,CTTTTGATAAAACA,tgttgaatctgcaagtggacatttggatagatttgaagatttcttt...,p11.1
255775,185076732,17244280,17244353,37,2.000000,74,chr13,atataaactagacagaagcattttcataaacttgtttgtgatgtgt...,TCAGCTAACAGACGTGGATCATTCTTTTGATACAGCA,gttttgaaaaacactttttgttgaatctgcaagtggacatttggat...,p11.1
255776,185076733,17302972,17303045,37,2.000000,74,chr13,ataaaaactagacagaagcattttcataaacttgtttgtgatgtgt...,TCAGCTAACAGACGTGAATCTTTCTTTTGATACAGCA,gttttgaaaaacactttttgttgaatctgcaagtggacatttggat...,p11.1

In [20]:
STRinvestigation_fp1 = "/home/androx/Documents/trabalho/datasets/STRdensInvestgation/cytobands_STRdens1.txt"
STRinvestigation_fp2 = "/home/androx/Documents/trabalho/datasets/STRdensInvestgation/STR_cytobandNotFound(>2cytobands).txt"
#writeNewtxt(STRinvestigation_fp1, citobands_df_dens1)
writeNewtxt(STRinvestigation_fp2, str_df_investigate)

# Separar os tandem repeats em dois datafiles, Short Tandem Repeats (STRs) e Long Tandem Repeats (LTRs)

In [21]:
strs_df = str_df.loc[str_df['PatternSize'] <= 6]
strs_df

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
0,184820957,10001,10468,6,77.125000,468,chr1,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,TAACCC,cgcggtaccctcagccggcccgcccgcccgggtctgacctgaggag...,p36.33
8,184820965,30855,30963,2,53.666668,109,chr1,gtcatggggtggggccctcattatagatctggtaagaaaagagaGC...,TC,tttcccaccaagtgaggatgcgaagagaaggtggctgtctgcaaac...,p36.33
10,184820967,44836,44876,4,10.000000,41,chr1,ccggggattgatatccagaatatacaagtaacacaaatatgtcaaa...,AAAT,tatttaaaaatcggcagaggacaggaatagacatttctcaggagac...,p36.33
11,184820968,50482,50513,2,16.000000,32,chr1,AGGATAATAAAGTTATGAAACCAATGCCACAAAACATCTGTCTCTA...,GT,AAGAGGGAGAGAGAGAAAATTTCACTCCCTCCATAAATCTCACAGT...,p36.33
16,184820973,54713,54817,4,25.666666,105,chr1,ccacagctttaatcaccatctaaacactaggggctctcaaaCCTTG...,TTTC,Tttaaggggcagggtctcactatgttgctgaggctggtctcaaact...,p36.33
...,...,...,...,...,...,...,...,...,...,...,...
1199615,186020572,57202848,57202903,1,56.000000,56,chrY,gattgcgccactgcactccagcctgggtgacagagcgagacgccgt...,A,CATCCAGCACTGATCCCAGGGGCCTGTTTCCTCGGCCTCAGGCTGA...,q12
1199617,186020574,57206370,57206740,6,60.299999,371,chrY,tcaactggaagaaagggtatcagtgattgaagatcaaatgaatgaa...,GGGTCA,ACCCTTTACAGCAGATGAAGGCCTCTCCCCAGCCAGAAAAGATGGA...,q12
1199623,186020580,57216407,57217320,6,150.222229,914,chrY,cctaatgcacacatgatacccaaaatataacacccacattcctcat...,TTAGGG,gtggtgtgtgggtgtgtgtgggtgtggtgtgtgtgggtgtggtgtg...,q12
1199624,186020581,57217317,57217414,6,16.375000,98,chrY,gttaggggttaggggttaggggttaggggttagggttagggttagg...,GGGTGT,TNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12
1199626,186020583,57217319,57217413,2,49.500000,95,chrY,taggggttaggggttaggggttaggggttagggttagggttagggt...,GT,gTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12

In [22]:
ltrs_df = str_df.loc[str_df['PatternSize'] > 6]
ltrs_df

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
1,184820958,10628,10800,29,5.965517,173,chr1,gcggtgctctccgggtctgtgctgaggagaacgcaactccgccgtt...,AGGCGCGCCGCGCCGGCGCAGGCGCAGAG,cacatgctagcgcgtcggggtggaggcgtggcgcaggcgcagagag...,p36.33
2,184820959,10823,10865,23,1.956522,43,chr1,aggcgcgccgcgccggcgcaggcgcagacacatgctagcgcgtcgg...,GAGGCGCGCCGCGCAGGCGCAGA,gcgcagagacacatgctaccgcgtccaggggtggaggcgtggcgca...,p36.33
3,184820960,10758,10997,76,3.210526,240,chr1,cgcagagaggcgcgccgcgccggcgcaggcgcagagaggcgcgccg...,GGCGCAGGCGCAGAGAGGCGCGCCGCGCCGGCGCAGGCGCAGAGAC...,cgcaagcctacgggcgggggttgggggggcgtgtgttgcaggagca...,p36.33
4,184820961,11226,11447,124,1.854839,222,chr1,cttgcagccgggcactacaggacccgcttgctcacggtgctgtgcc...,CGCCCCCTGCTGGCAACTAGGGAAACTGCAGGGCCCTCTTGCTCAA...,CCAACAGTACTGGCGGATTATAGGGAAACACCCGGAGCATATGCTG...,p36.33
5,184820962,11167,11448,61,4.714286,282,chr1,gcggcgcagagacgggtagaacctcagtaatccgaaaagccgggat...,CGCCCCCTGCTGGCAGCTAGGGACACTGCAGGGCCCTCTTGCTCAA...,CAACAGTACTGGCGGATTATAGGGAAACACCCGGAGCATATGCTGT...,p36.33
...,...,...,...,...,...,...,...,...,...,...,...
1199620,186020577,57209487,57209536,20,2.500000,50,chrY,CCCCTTATTCCACCCATGGGAGGTGCACACAAGGTCTTGTTGGCTG...,TGCAGGTCCCTGCCAAATCT,AGAGAACTACTTCTATGTGCCAGACCTGGGCCAGGTGCCTGAGATT...,q12
1199621,186020578,57215131,57215306,62,2.875000,176,chrY,caaacagcatatgCTCCTGGTGTTTCCCTATAATCCgccactactg...,AGCAAGAGGACCCTGCAGTGTCCCCAGCTGCCAGCAGGCGGGCGTG...,ctaagcaagagagccctgcagttgccctagtcgccagcagggggcg...,q12
1199622,186020579,57215631,57215892,29,9.034483,262,chrY,gcgtctctgcgcctgcgccacgcctccacccctggacgcgctagca...,TCTCTGCGCCTGCGCCGGCGCGGCGCGCC,ttgcgacggccgagttgcgttctcgtcagcacagagcggcagagca...,q12
1199625,186020582,57217317,57217415,13,7.714286,99,chrY,gttaggggttaggggttaggggttaggggttagggttagggttagg...,GGGTGTGGTGTGT,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12
1199627,186020584,57217317,57217415,53,1.924528,99,chrY,gttaggggttaggggttaggggttaggggttagggttagggttagg...,GGGTGTGGTGTGTGGGTGTGGGTGGGTGGGTGTGGTGTGTGGGTGT...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,q12

In [23]:
strs_write = "/home/androx/Documents/trabalho/datasets/STR/HomosapiensHG38_jan2016/humanGenome_STRs.txt"
ltrs_write = "/home/androx/Documents/trabalho/datasets/STR/HomosapiensHG38_jan2016/humanGenome_LTRs.txt"

writeNewtxt(strs_write, strs_df)
writeNewtxt(ltrs_write, ltrs_df)

# Calcular as densidades de cada um dos subcojuntos

In [24]:
citobands_df = citobands_df.drop("STRs_density", axis = 1)

In [25]:
citobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density
0,chr1,0,2299999,p36.33,gneg,2299999,0.088
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056
...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026
862,chrY,26600000,57227414,q12,gvar,30627414,0.006

In [26]:
calc_STRDensity(citobands_df, strs_df, "STRs_dens")

searching cytobands in chromossome:  chr1
searching cytobands in chromossome:  chr10
searching cytobands in chromossome:  chr11
searching cytobands in chromossome:  chr12
searching cytobands in chromossome:  chr13
searching cytobands in chromossome:  chr14
searching cytobands in chromossome:  chr15
searching cytobands in chromossome:  chr16
searching cytobands in chromossome:  chr17
searching cytobands in chromossome:  chr18
searching cytobands in chromossome:  chr19
searching cytobands in chromossome:  chr2
searching cytobands in chromossome:  chr20
searching cytobands in chromossome:  chr21
searching cytobands in chromossome:  chr22
searching cytobands in chromossome:  chr3
searching cytobands in chromossome:  chr4
searching cytobands in chromossome:  chr5
searching cytobands in chromossome:  chr6
searching cytobands in chromossome:  chr7
searching cytobands in chromossome:  chr8
searching cytobands in chromossome:  chr9
searching cytobands in chromossome:  chrM
searching cytobands in chromossome:  chrX
searching cytobands in chromossome:  chrY

In [27]:
calc_STRDensity(citobands_df, ltrs_df, "LTRs_dens")

searching cytobands in chromossome:  chr1
searching cytobands in chromossome:  chr10
searching cytobands in chromossome:  chr11
searching cytobands in chromossome:  chr12
searching cytobands in chromossome:  chr13
searching cytobands in chromossome:  chr14
searching cytobands in chromossome:  chr15
searching cytobands in chromossome:  chr16
searching cytobands in chromossome:  chr17
searching cytobands in chromossome:  chr18
searching cytobands in chromossome:  chr19
searching cytobands in chromossome:  chr2
searching cytobands in chromossome:  chr20
searching cytobands in chromossome:  chr21
searching cytobands in chromossome:  chr22
searching cytobands in chromossome:  chr3
searching cytobands in chromossome:  chr4
searching cytobands in chromossome:  chr5
searching cytobands in chromossome:  chr6
searching cytobands in chromossome:  chr7
searching cytobands in chromossome:  chr8
searching cytobands in chromossome:  chr9
searching cytobands in chromossome:  chrM
searching cytobands in chromossome:  chrX
searching cytobands in chromossome:  chrY

In [28]:
citobands_df

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,STRs_dens,LTRs_dens
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.006,0.084
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084,0.014,0.079
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056,0.013,0.051
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049,0.013,0.042
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056,0.011,0.049
...,...,...,...,...,...,...,...,...,...
858,chrY,12400000,17099999,q11.221,gpos50,4699999,0.037,0.014,0.029
859,chrY,17100000,19599999,q11.222,gneg,2499999,0.062,0.016,0.053
860,chrY,19600000,23799999,q11.223,gpos50,4199999,0.082,0.006,0.078
861,chrY,23800000,26599999,q11.23,gneg,2799999,0.026,0.009,0.021
862,chrY,26600000,57227414,q12,gvar,30627414,0.006,0.002,0.004

In [29]:
cytobandLTRS_write = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_STRs_LTRs.txt"
writeNewtxt(cytobandLTRS_write, citobands_df)

In [30]:
strs_chr1_p11_1 = strs_df.loc[(strs_df['FastaHeader'] == "chr1") & (strs_df['Citoband'] == "p11.1")]
strs_chr1_p11_1

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
50362,184871319,121856798,121856849,6,8.666667,52,chr1,ATGGAATGTAAGCAGAAGCACTAGAACATATATATGTATATtctcg...,CTCTCT,ttcCAGGAaagatacagattgattcgctttcatataaagacatcaa...,p11.1
50379,184871336,121924663,121924699,1,37.000000,37,chr1,agatgccgccactgcactccagcctgggcgacagagcgagactccg...,A,gagcgtttcaacctgaactcacaagggaaggttcaactctgtcagt...,p11.1
50410,184871367,122102705,122102756,6,8.666667,52,chr1,ATGGAATGTAAGCAGAAGCACTAGAACATATATATGTATATtctcg...,CTCTCT,ttcCAGGAaagatacagattgattcgctttcatataaagacatcaa...,p11.1
50412,184871369,122109748,122109785,1,38.000000,38,chr1,agatgccgccactgcactccagcctgggcgacagagcgagactccg...,A,gagcgtttcaacctgaactcacaagggaaggttcaactctgtcagt...,p11.1
50413,184871370,122125427,122125464,1,38.000000,38,chr1,ttcaactgacagagttgaaccttcccttgtgagttcaggttgaaac...,T,ggagacggagtctcgctctgtcgcccaggctggagtgcagtggcgg...,p11.1

In [31]:
ltrs_chr1_p11_1 = ltrs_df.loc[(ltrs_df['FastaHeader'] == "chr1") & (ltrs_df['Citoband'] == "p11.1")]
ltrs_chr1_p11_1

,Repeatid,FirstIndex,LastIndex,PatternSize,CopyNumber,ArrayLength,FastaHeader,FlankingLeft50,Pattern,FlankingRight50,Citoband
50331,184871288,121742260,121775784,340,98.484344,33525,chr1,aacacaagcctcacaaaggagtttttgagaatgcttctgtttactt...,TGCTAGACAGAAGAATTCTCAGTAACTTCCTTGTGTTGTGTGTATT...,caagcgctttggggccaaaggcagaaaaggaaatatcttcgtagaa...,p11.1
50332,184871289,121758074,121776357,1019,17.938562,18284,chr1,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,GACTTGAAACACTCTTTTTGTGGAATTTGCAAGTGGAGATTTCAGC...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,p11.1
50333,184871290,121758074,121776357,1359,13.464950,18284,chr1,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,GACTTGAAACACTCTTTTTGTGGAATTTGCAAGTGGAGATTTCAGC...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,p11.1
50334,184871291,121758074,121776357,340,53.826668,18284,chr1,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,GACTTGAAACACTCTTTTTGTGGAATTTGCAAGTGGAGATTTCAGC...,NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,p11.1
50335,184871292,121776498,121781075,171,26.837004,4578,chr1,NNNNNNNNNNTGAGAGagatatttccttttccccccatgcctcgaa...,TCCAAATATCCACTTGCAGATTCTACAAAAAGAGTGTTTCAAAACT...,ttctttcctttACTANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...,p11.1
...,...,...,...,...,...,...,...,...,...,...,...
50405,184871362,121972546,121974216,338,4.937143,1671,chr1,ctttcaggcctgcggtggaaaaagaaatatctttcacataaaactt...,AGAAGCATTCTCAGAACCTTCTTCGTGATGATTGCATTCAACTCAC...,atatcctcccgtaaaagtaaacagagctttctcaaaactcctttgt...,p11.1
50406,184871363,121974675,121976414,170,10.240438,1740,chr1,TTTCTTTTAGTTAAGGGAGGTTTAtcccttttcaatgaatccttcg...,GTCCAAATATCCACTTGCAGATTCTACAAAAAGAGTGTTTCAAAAC...,ctcagaacctcagaagTGGAAGAGATCAATCCCGGTGAGTAGAATN...,p11.1
50407,184871364,121974832,121976401,338,4.603352,1570,chr1,aggcatcagtctttttttagatgaagatattccctttaatgcgata...,TCAAAGAGGTCCAAATATCCACTTGCAGATTCTACAAAAAGAGTGT...,tcgagtgtctcaactcagaacctcagaagTGGAAGAGATCAATCCC...,p11.1
50411,184871368,122102705,122102756,8,6.500000,52,chr1,ATGGAATGTAAGCAGAAGCACTAGAACATATATATGTATATtctcg...,CTCTCTCT,ttcCAGGAaagatacagattgattcgctttcatataaagacatcaa...,p11.1
50414,184871371,122367581,122367635,29,2.034483,55,chr1,ctagacagaagccttctcagaaacttctctgtgatgattgcatgca...,ACAGTGTTGAACACTCTCTTTGTGATAGA,tctgcaagtggatatgtggacctctgtgaagatttccttggaaaca...,p11.1

In [32]:
cb_chr1 = citobands_df.loc[citobands_df['Chromossome'] == "chr1"]
cb_chr1

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,STRs_dens,LTRs_dens
0,chr1,0,2299999,p36.33,gneg,2299999,0.088,0.006,0.084
1,chr1,2300000,5299999,p36.32,gpos25,2999999,0.084,0.014,0.079
2,chr1,5300000,7099999,p36.31,gneg,1799999,0.056,0.013,0.051
3,chr1,7100000,9099999,p36.23,gpos25,1999999,0.049,0.013,0.042
4,chr1,9100000,12499999,p36.22,gneg,3399999,0.056,0.011,0.049
...,...,...,...,...,...,...,...,...,...
58,chr1,226800000,230499999,q42.13,gneg,3699999,0.040,0.009,0.036
59,chr1,230500000,234599999,q42.2,gpos50,4099999,0.024,0.007,0.020
60,chr1,234600000,236399999,q42.3,gneg,1799999,0.040,0.010,0.035
61,chr1,236400000,243499999,q43,gpos75,7099999,0.024,0.008,0.019
62,chr1,243500000,248956421,q44,gneg,5456421,0.036,0.007,0.032

In [34]:
cb_chr1.loc[cb_chr1['STRs_dens'] == 0.000]

,Chromossome,First_index,Last_index,Citoband,Unkown,Size,STR_Density,STRs_dens,LTRs_dens
33,chr1,121700000,123399999,p11.1,acen,1699999,0.965,0.0,0.965
35,chr1,125100000,143199999,q12,gvar,18099999,0.003,0.0,0.003

### Verificação de padrão STR no chromossoma do genoma de referência

In [18]:
def pattern_matching():
    file1 = "/home/androx/Downloads/STR_patern_verification/Chr13_16003398_18051248.txt"
    file2 = "/home/androx/Downloads/STR_patern_verification/pattern171.txt"
    f1 = open(file1, "r")
    f2 = open(file2, "r")
    f1read = f1.read()
    f2read = f2.read()
    similarities = []
    for k in range (50):
        similarity = 0
        for i in range(171+1):
            if f1read[k*171+i]== f2read[i]:
                similarity+=1
        similarities.append(similarity)
    f1.close()
    f2.close()
    return similarities

In [ ]:
pattern_matching()